### ISSUE TITLE
request for subref should not crash

### ISSUE THREAD

**Issue by balmas** [Capitains/Ahab#14]
until #1 is fully supported (if it ever is) we should at least have requests which include subrefs return the passage that contains the subref (probably with an HTTP 303 see other status)

**Comment by PonteIneptique** [comment]
Trying 
`http://localhost:8080/exist/restxq/cts?request=GetPassage&inv=thibault3&urn=urn:cts:latinLit:phi0959.phi002.perseus-lat2:1.1@Penelope[1]-1.5@Ele[1]`
Show that this is already supported.
To my great surprise I should say.
